name: ML Model Evaluation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install scikit-learn numpy pytest

      - name: Train model
        run: python src/train.py

      - name: Run tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Evaluate model
        run: python src/evaluate.py

      - name: Upload metrics report
        uses: actions/upload-artifact@v4
        with:
          name: metrics-report
          path: metrics.json
